### PR TITLE
Add files via upload

### LINKED ISSUE #33: Tests für Admin-Seite schreiben

### PR DESCRIPTION
**Pull request by roldka**

### CODE REVIEW

**Review by phie73 — CHANGES_REQUESTED** [review]
Great work :+1:. Is it possible to abstract the webdriver executable_path?

**Comment by roldka** [comment]
fixed the executable_path and added the corresponding driver

**Comment by haasmi** [comment]
Hey, could you also please write a little readme for your tests? E.g. what pip installs are needed and how to install the webdriver (https://stackoverflow.com/a/61084589)
P.S. please remove the binary of the webdriver

**Comment by roldka** [comment]
Changed the code so no executable path is necessary anymore. Instead, a module is imported to install geckodriver.
I also added a new section to the README and removed all unwanted files.

**Comment by phie73** [comment]
the stuff with the gecko driver works. But all tests fail or throw exceptions.

**Comment by roldka** [comment]
did mess up the commit message. what i did: tests should now be running. i removed one test since i still got problems with it. but all the tests that are on right now, should be fine.

**Comment by roldka** [comment]
edited readme to solve conflict. will insert that part on master branch readme later.

**Review by phie73 — APPROVED** [review]

**Pull request merged**
